### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by LappleApple** [zalando-incubator/funelo#2]
Hey guys -- was this a Hack Week project? Do you have plans to develop it further? Is it useful/almost-useful to non-Zalandos in its current state?

**Comment by arturmkrtchyan** [comment]
Hey Lauri, yep this was a hack week project. Initial idea was to develop and use in and out zalando, but we haven't used it yet in zalando. I don't have enough time currently to develop it further I would like to park it somewhere and restart when there is a real need and time. I'm fine parking it under my account only if it helps.

**Comment by LappleApple** [comment]
Parking it on your account might be a good idea for now. But let's think about how to get people to help you with this, if you think it's worth the effort.

**Comment by LappleApple** [comment]
@arturmkrtchyan Hey, in light of the Incubator being created I'm wondering if you'd be okay with me transferring the repo there for now, until you can revisit this project. Just LMK!

**Comment by arturmkrtchyan** [comment]
@LappleApple definitely :) I just remember my first day in the guild meeting mentioning that we need incubator. I'm happy that we have it now. feel free to move it.

**Comment by LappleApple** [comment]
Done! And all your privileges transferred, so all should be good. :)
